#!/bin/bash
#/usr/lib/check_mk_agent/local

#Get data
bgp4_sessions_up=$(birdc s p|grep BGP|grep -c up)
bgp6_sessions_up=$(birdc6 s p|grep BGP|grep -c up)
conntrack=$(conntrack -C);

#Output
##BGP
echo "P BGP-Sessions IPv4=$bgp4_sessions_up;4:4;3:5|IPv6=$bgp6_sessions_up;4:4;3:5"
##Conntrack
echo "0 Conntrack Conntrack=$conntrack;";
